name: Déploiement sur mon serveur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt GitHub
        uses: actions/checkout@v4

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Construction de l'image Docker
        run: docker build -t flexxdawg/test-cicd-1 .

      - name: Push de l'image Docker sur Docker Hub
        run: docker push flexxdawg/test-cicd-1

      - name: Déploiement via SSH avec mot de passe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull flexxdawg/test-cicd-1
            docker stop test-cicd-1 || true
            docker rm test-cicd-1 || true
            docker run -d --name test-cicd-1 -p 80:80 flexxdawg/test-cicd-1
